### ISSUE TITLE
why not use Eign::VectorXd but use array to implement vector? faster? less 3rd-party labrary？

### ISSUE THREAD

**Issue by tiemuhua** [ZJU-FAST-Lab/LBFGS-Lite#4]

**Comment by ZhepeiWang** [comment]
It is OK to use Eigen::VectorXd in this code. But originally, we need to deploy this into different platforms except for x86. Less 3rd lib mean more flexibility.

**Comment by ZhepeiWang** [comment]
Hey, I have rewrite the code using Eigen. It is much faster now if the dimension of "x" is large. I am about to push a new version which depends Eigen.
