### ISSUE TITLE
what is the purpose of using the parameter "loop"

### ISSUE THREAD

**Issue by tiemuhua** [ZJU-FAST-Lab/LBFGS-Lite#5]
in function lbfgs_optimize, there is a parameter "loop", howerver, after this parameter is set to zero, the loop will break, so why not just break directly, what is the purpose of the parameter "loop"
![image](https://user-images.githubusercontent.com/46767782/147526675-1045c373-874f-46e6-b318-a6983dd9ddb7.png)

**Comment by ZhepeiWang** [comment]
Yes, you are right. This is a redundant variable in the current version. I'll remove it. Thank you!
