### ISSUE TITLE
why loop of i only has variable j

### ISSUE THREAD

**Issue by tiemuhua** [ZJU-FAST-Lab/LBFGS-Lite#6]
![image](https://user-images.githubusercontent.com/46767782/147536573-6f425ea4-7968-47e3-bce3-d95b5ad10b89.png)
from line 1496 to line 1519, this two for loops has variable i, but in the loop body, there is no i, only j, why?
1496行到1519行这两个for循环是关于i的，但是循环体里面为什么只有j没有i？

**Comment by ZhepeiWang** [comment]
These code blocks are the two-loop recursions of limited memory update (https://en.wikipedia.org/wiki/Limited-memory_BFGS). The variable "i" is just used for counting the number of loops. It is the variable "j" that sequentially accesses the memorized "s" and "y".

**Comment by ZhepeiWang** [comment]
Appreciate your review of this repo. I close it here but any further issue is welcomed.
