### ISSUE TITLE
what does the word "brackt" means in this project?

### ISSUE THREAD

**Issue by tiemuhua** [ZJU-FAST-Lab/LBFGS-Lite#7]
i can not understand what does the variable "brackt" means in this project。百度翻译说brackt是支架、括号的意思，我无法理解这个变量是干什么的，还有line_search_morethuente里面的stage变量，这两个变量是什么意思，支架和舞台？

**Comment by ZhepeiWang** [comment]
"brackt" is the abbr. of "bracket". It means a point satisfying some conditions are bracketed by an interval.
"stage" is just an auxiliary variable to determine which phase of the procedure is occuring.

Nonetheless, I'm about to remove "line_search_morethuente" becuase it only suits well-conditioned functions. It does reduce the number of function call, but sometimes negligible. It is the most fragile part in this lib even correctly implemented.
