### ISSUE TITLE
您好，想请教一下关于学习优化的问题

### ISSUE THREAD

**Issue by dssdyx** [ZJU-FAST-Lab/LBFGS-Lite#8]
打扰大佬了，想跟您请教一下怎么学习有关凸优化和非线性优化的知识，请问有推荐的书籍么

**Comment by ZhepeiWang** [comment]
Nocedal - Numercial Optimization
Nesterov - Lectures on Convex Optimization
Nemirovski - Lectures on Modern Convex Optimization
Wen - Optimization: Modeling, Algorithm and Theory (in Chinese)

**Comment by dssdyx** [comment]
> Nocedal - Numercial Optimization Nesterov - Lectures on Convex Optimization Nemirovski - Lectures on Modern Convex Optimization Wen - Optimization: Modeling, Algorithm and Theory (in Chinese)

非常感谢！
